---
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create web root directory
  file:
    path: "{{ web_root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Deploy nginx site configuration
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart nginx

- name: Ensure nginx is running and enabled
  systemd:
    name: nginx
    state: started
    enabled: yes
- name: Allow Nginx HTTP/HTTPS through UFW
  ufw:
    rule: allow
    name: 'Nginx Full'
